export const contactListActions = {
  FETCH_CONTACTS_START: "FETCH_CONTACTS_START",
  FETCH_CONTACTS_SUCCESS: "FETCH_CONTACTS_SUCCESS",
  FETCH_CONTACTS_FAIL: "FETCH_CONTACTS_FAIL",
  SORT_LASTNAME: "SORT_LASTNAME",
};
